/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC1400TokensRecipient__factory } from "./IERC1400TokensRecipient__factory";
export { IERC1400TokensSender__factory } from "./IERC1400TokensSender__factory";
