/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1400TokensValidator } from "./ERC1400TokensValidator";
export type { IMinterRole } from "./IMinterRole";
