/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1400TokensValidatorMock } from "./ERC1400TokensValidatorMock";
export type { IMinterMock } from "./IMinterMock";
