/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as clockSol from "./Clock.sol";
export type { clockSol };
import type * as erc1400TokensValidatorMockSol from "./ERC1400TokensValidatorMock.sol";
export type { erc1400TokensValidatorMockSol };
import type * as fakeErc1400MockSol from "./FakeERC1400Mock.sol";
export type { fakeErc1400MockSol };
import type * as minterRoleMockSol from "./MinterRoleMock.sol";
export type { minterRoleMockSol };
export type { AllowlistMock } from "./AllowlistMock";
export type { BlocklistMock } from "./BlocklistMock";
export type { CertificateSignerMock } from "./CertificateSignerMock";
export type { ERC1400TokensRecipientMock } from "./ERC1400TokensRecipientMock";
export type { ERC1400TokensSenderMock } from "./ERC1400TokensSenderMock";
export type { PauserMock } from "./PauserMock";
